# Generated by Django 6.0.3 on 2026-03-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(help_text='Key or path of the file in the storage bucket.', max_length=255)),
                ('public_url', models.URLField(help_text='Public URL to access the audio file.')),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('duration_seconds', models.FloatField(help_text='Duration in seconds, if known.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('front', 'Front'), ('back', 'Back')], max_length=10)),
            ],
        ),
    ]
