# Generated by Django 6.0.3 on 2026-03-14 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_assets', '0001_initial'),
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audioasset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashcardaudio',
            name='audio_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_links', to='media_assets.audioasset'),
        ),
        migrations.AddField(
            model_name='flashcardaudio',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_links', to='study.flashcard'),
        ),
        migrations.AlterUniqueTogether(
            name='flashcardaudio',
            unique_together={('flashcard', 'audio_asset', 'side')},
        ),
    ]
